server:
  servlet:
    context-path: /springboot/  # 根路径，必须是/开头的
  port: 8081

spring:
  datasource:  # 数据库配置
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: admin

